### ISSUE TITLE
VLAN Settings Blank in Version 3.3-138

### ISSUE THREAD

**Issue by ike200000** [Jackysi/advancedtomato#206]
ASUS RT-AC66U
Version 3.3-138

Just upgraded from 137 to 138 and the VLAN settings are blank. I restored default settings and cleared NVRAM. This did not fix anything.

![capture](https://cloud.githubusercontent.com/assets/21015625/17646585/58abe006-619e-11e6-806f-332ed1b3a69d.JPG)

**Comment by Jackysi** [comment]
Can you open up F12 Console and try that again?

**Comment by ike200000** [comment]
![image](https://cloud.githubusercontent.com/assets/21015625/17648966/86477028-61f5-11e6-947c-c7396f63381d.png)

**Comment by Jackysi** [comment]
Hmm that's hard to debug without device. Sorry, I can't fix it like that.

**Comment by ike200000** [comment]
Ok so the first error when loading the page is on the jquery.min.js script. "SyntaxError: Unexpected Token }"
![image](https://cloud.githubusercontent.com/assets/21015625/17650260/49a878fc-6217-11e6-864a-f9ac6a670373.png)

Digging further shows that the "port_vlan_supported" is undefined. This is strange since it is defined in the NVRAM.
![image](https://cloud.githubusercontent.com/assets/21015625/17650283/d9c02a2a-6217-11e6-8878-e2ea5ef48fe3.png)

![image](https://cloud.githubusercontent.com/assets/21015625/17650304/4d2b46b6-6218-11e6-86a2-47a44787b5c3.png)
...
![image](https://cloud.githubusercontent.com/assets/21015625/17650301/3219ef12-6218-11e6-93da-8a9fbfb274af.png)

Continuing on shows that trunk_vlan_supported is also not defined multiple times.
![image](https://cloud.githubusercontent.com/assets/21015625/17650308/6ba2e2a2-6218-11e6-8f89-82f6dd23a0e0.png)
![image](https://cloud.githubusercontent.com/assets/21015625/17650311/901f471a-6218-11e6-8e4e-b75447c681b8.png)

Then another "port_vlan_supported" error.
![image](https://cloud.githubusercontent.com/assets/21015625/17650312/a5dde796-6218-11e6-94ce-a9a8cd0badbc.png)

Next is a tomato.js null error on the style property
![image](https://cloud.githubusercontent.com/assets/21015625/17650339/2b84778e-6219-11e6-8cf2-d6c0395029fd.png)

**Comment by BrainDedd** [comment]
Just want to add my +1 on this. ASUS RT-N66U.

**Comment by Jackysi** [comment]
I have N66U + latest firmware and I don't see this problem... How is that possible?

**Comment by pdonadeo** [comment]
Same problem with   Asus RT-N16

![screenshot from 2016-08-16 02-37-46](https://cloud.githubusercontent.com/assets/242049/17684314/d788923a-635a-11e6-87e5-812bdc981af5.png)

**Comment by pdonadeo** [comment]
If I can help in any way, tell me what you need to debug this situation.

**Comment by Jackysi** [comment]
Fixed: https://github.com/Jackysi/advancedtomato-gui/commit/1bda0c3e0abdab9fdf41f72fbd68cb73f475a0ec

**Comment by BrainDedd** [comment]
Hmmm ... we've all forgotten to close a comment block :smile: 
Look forward to grabbing the new version :+1:

**Comment by Jackysi** [comment]
I've uploaded new images with the above fix. The naming is the same however the MD5 checksum and the Images are new. Please try and report.

**Comment by BrainDedd** [comment]
Working :+1:

**Comment by bgt59** [comment]
Hi,
It seems this issue is still present for WNR3500Lv2 too.

**Comment by ishrakr** [comment]
Same issue on the N10U. 
![screenshot_2](https://cloud.githubusercontent.com/assets/642351/19246706/7e37d1b2-8f49-11e6-8011-85be302c2b02.png)

**Comment by nsenica** [comment]
I can confirm that this is still happening on a N10U, the trx was downloaded yesterday from the main website.

**Comment by ChrisHughes** [comment]
Still happening on an RT-N53

**Comment by Jackysi** [comment]
can someone post whole page source (not by using view source, but using F12 -> click on <html> -> edit html and copy all and paste here using "INSERT CODE" - Chrome, Idk for other browsers). I will give it a look but i'm not sure what is missing.

**Comment by nsenica** [comment]
Here it goes.

I think I can point you directly to the problem, just search for 

```
<input type="hidden" name="lan_ifnames">
```

And you'll see that this starts in the middle of the vlg.dataToView JS declaration.

Let me know if you need more information

Thanks
Nuno

**EDITED BY JACKY (REMOVED CODE)**

**Comment by nsenica** [comment]
I've also checked inside the router, and the advanced-vlan.asp file has only 653 lines, and it looks like this: 

```
(data[ COL_P3 ].toString() != '0') ? 'Yes' : '',
(data[ COL_P3T ].toString() != '0') ? 'On' : '',
(data[ COL_P4 ].toString() != '0') ? 'Yes' : '',
(data[ COL_P4T ].toString() != '0') ? 'On' : '',
(data[ COL_VID_DEF ].toString() != '0') ? '*' : '',
[ '', 'WAN', 'LAN (br0)', 'LAN1 (br1)', 'LAN2 (br2)', 'LAN3 (br3)', 'WAN2'
<input type="hidden" name="lan_ifnames">
<input type="hidden" name="lan1_ifnames">
<input type="hidden" name="lan2_ifnames">
<input type="hidden" name="lan3_ifnames">
<input type="hidden" name="vlan0vid">
<input type="hidden" name="vlan1vid">
<input type="hidden" name="vlan2vid">
```

Which confirms the problem. My guess, if I may, is that the firmware image on the website is not updated. 

Regards,
Nuno

**Comment by Jackysi** [comment]
Thanks! I will compare with my version of the file and then see if the problem is in both or just the version from the web site. I do believe too that I forgot to recompile ALL firmware's because I thought the issue is only part of ARM. Not sure.

I have some updates so I'll release 3.4-138 with this fix soon.

**Comment by nsenica** [comment]
Awesome @Jackysi :) Let me know if you need further investigation from my side.

**Comment by Jackysi** [comment]
I could use a tester, I just need 1 router name to compile fast 1 image. I think I've found out the issue, it was huge :D

**Comment by nsenica** [comment]
I can test it, no problem :) Mine is a RT-N10U, if you want to compile the image I can test it later on.

**Comment by Jackysi** [comment]
MD5: c46ceee44cace92ff9145a67c3bca34c 
https://advancedtomato.com/data/tomato-K26-1.28.AT-RT-N5x-MIPSR2-3.3-138-Max.trx

I think that should be the one

**Comment by nsenica** [comment]
Hi @Jackysi 

I'm really sorry to tell you, but that is broken as well :( Upgrade via UI didn't work, I could ping the router but I couldn't access it via http or ssh.

I needed to do a regular flash, uploaded the firmware via Asus Firmware Restoration tool, and I got the same thing again :(

Any idea ?

**Comment by Jackysi** [comment]
So this image failed completely? Ahm that's rather strange

**Comment by nsenica** [comment]
I'm not sure what you mean with "failed completely", but I suppose that after the firmware restoration it loaded correctly. 

Can you provide a image with some easily identifiable change so we are sure if it was loaded correctly or not ?

Also, it seems that the asp files are somehow preprocessed, could it be that the pre-processor doesn't like the comments within the JS section ? Can you remove them and see if it works ?

Thanks

**Comment by Jackysi** [comment]
The problem is not preprocessor (which actually must be there) so the firmware fits certain routers. The problem is non-closed comment in the javascript which has been fixed in this commit: https://github.com/Jackysi/advancedtomato-gui/commit/1bda0c3e0abdab9fdf41f72fbd68cb73f475a0ec

Now the only problem is images on the web site don't include that fix.

**Comment by nsenica** [comment]
Ok. I can help you testing it, just let me know when.

:)

**Comment by nsenica** [comment]
@Jackysi , I noticed something that I'm not sure if it doesn't break somewhere in the build process.

There are `/* MULTIWAN-BEGIN */` and `/* MULTIWAN-END */` in the middle of HTML, in HTML `/*` and `*/` don't have any meaning as comment delimiters, could the pre processor be breaking the build due to interpreting that as regular comments ?

Just wondering.

**Comment by Jackysi** [comment]
I have already given you fix for the VLAN page error. I don't really understand what are you talking about further ^^

**Comment by nsenica** [comment]
hmm I'm not sure I understand what you say, but the image you provided in this [comment](https://github.com/Jackysi/advancedtomato/issues/206#issuecomment-254802985) didn't work, as I stated before. So I assumed that the fix was not working.

**Comment by Jackysi** [comment]
You said the image I attached  didn't flash properly so it broke your router no? How do you assume that VLAN page wasn't fixed? If  VLAN page had error it wouldn't brick whole router cause of it. I'm not sure why your router would brick, but I flashed the image on my Asus RT-N66U and the VLAN page works good.

**Comment by Jackysi** [comment]
P.S.: Whats the name of image you usually flash on your N10? I have some more images but idk which to give you

**Comment by nsenica** [comment]
The image didn't upgrade (via UI) properly at first, but then I managed to flash it using the Asus Firmware Restoration app, and after that the VLANs page is/was still broken. 
Maybe the flash didn't work and it loaded what I had there initially. I can try to flash a previous version (127) first, and then try to upgrade to this one you provided again.

I usually flash from http://tomato.groov.pl/ and for this model K26RT-N, this was the first time I tried flashing your firmware.

**Comment by HFsi** [comment]
Exactly same problem for a Linksys E2500 V3

**Comment by barkster** [comment]
Is this fixed for RT-N16, I reflashed with latest download and mine are still blank

**Comment by Jackysi** [comment]
the fix will come with 3.4-138 or 3.4-139

**Comment by charsi** [comment]
I am seeing this issue in WNR3500Lv2 - 3.3-138. Is there anything I can change without having to build an image from scratch to get this working for the time being? 
Happy to do some testing too.
